"""
Writes every number reported in the paper as a LaTeX macro (analysis/numbers.tex), read from the experiment
result files under RESULTS_ROOT. A missing key raises an error.
Requires analysis/two_sided_pvalues.json (analysis/two_sided_pvalues.py).
"""
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "src"))
import config  # noqa: E402

X = config.RESULTS_ROOT
lines = ["% AUTO-GENERATED by paper_tkde/make_numbers.py -- do not edit by hand"]
WORD = {1: "One", 3: "Three", 4: "Four"}
DS = {"el_friends": "Friends", "el_emotionpush": "EmotionPush", "m3ed": "Mthreeed"}


def mac(name, val):
    assert name.isalpha(), name
    # \xspace: keep the space after the macro when a word follows (requires \usepackage{xspace})
    lines.append(f"\\newcommand{{\\{name}}}{{{val}\\xspace}}")


def f(x, nd=2, sign=True):
    if round(x, nd) == 0:
        return f"{0:.{nd}f}"
    s = f"{x:+.{nd}f}" if sign else f"{x:.{nd}f}"
    return s.replace("-", "$-$")


def fp(p, n):
    return f"\\ensuremath{{<}}{1 / (n + 1):.3f}" if p == 0 else f"{p:.3f}"


# two-sided empirical p-values (median-centred; two_sided_pvalues.py) replace the stored one-sided ones
P2 = json.loads((HERE / "two_sided_pvalues.json").read_text())

# ---- E27e: hard-mark estimator
e = json.loads((X / "E27e/E27e_results.json").read_text())
assert P2["E27e_n_reps"] == e["config"]["N_REPS_A"]
mac("NRepsNullHard", f"{e['config']['N_REPS_A']:,}".replace(",", "{,}"))
mac("NRepsPower", str(e["config"]["N_REPS_C"]))
for key, pl in (("full", 1), ("p3_5", 3), ("p4_5", 4)):
    mac(f"RealGammaWcPl{WORD[pl]}", f(e["real_gamma"][key]))
for model in ("linked", "indep"):
    for pl in (1, 3, 4):
        k = f"wc_full_{model}_pl{pl}_wc"
        if k in e["scheme_A_prime"]:
            v = e["scheme_A_prime"][k]
            p = e["scheme_A_prime"]["emp_p_" + k]
            base = f"NullHard{model.capitalize()}WcPl{WORD[pl]}"
            mac(base + "Mean", f(v["mean"]))
            mac(base + "Sd", f(v["std"], sign=False))
            mac(base + "P", f(P2["E27e_schemeA"][f"{model}_pl{pl}_wc"]["p"], 3, sign=False))
    k = f"rh_full_{model}_pl1_rh"
    if k in e["scheme_A_prime"]:
        v = e["scheme_A_prime"][k]
        p = e["scheme_A_prime"]["emp_p_" + k]
        mac(f"NullHard{model.capitalize()}RhPlOneMean", f(v["mean"]))
        mac(f"NullHard{model.capitalize()}RhPlOneSd", f(v["std"], sign=False))
        mac(f"NullHard{model.capitalize()}RhPlOneP", f(P2["E27e_schemeA"][f"{model}_pl1_rh"]["p"], 3, sign=False))
GAM = {"g0p0": "Zero", "gm0p4": "MinusFour", "gm0p8": "MinusEight"}
for pipe, tag in (("oracle", "Oracle"), ("obs", "Obs")):
    for pl in (1, 3, 4):
        for g, gt in GAM.items():
            k = f"obs_{pipe}_pl{pl}_{g}"
            if k in e["scheme_C_prime"]:
                v = e["scheme_C_prime"][k]
                mac(f"Power{tag}Pl{WORD[pl]}Gamma{gt}Mean", f(v["mean"]))
                mac(f"Power{tag}Pl{WORD[pl]}Gamma{gt}Sd", f(v["std"], sign=False))
mac("FlipRateLinkedPct", f"{100 * e['flip_fracs']['flip_frac_l']:.1f}")
mac("CorrHobsHlat", f(e["mean_corr_C"], sign=False))

# ---- E28: soft-mark estimator
s = json.loads((X / "E28/E28_results.json").read_text())
mac("NRepsNullSoft", str(s["config"]["N_REPS"]))
for k, v in s["real_gammas"].items():
    typ, pl = k.split("_pl")
    mac(f"RealSoftGamma{typ.capitalize()}Pl{WORD[int(pl)]}", f(v))
for k, v in s["null_distribution"].items():
    typ, model, pl = k.split("_")
    base = f"NullSoft{model.capitalize()}{typ.capitalize()}Pl{WORD[int(pl[2:])]}"
    mac(base + "Mean", f(v["mean"]))
    mac(base + "Sd", f(v["sd"], sign=False))
# Gate G1: accuracy-linked null, within-cell soft-mark gamma (pl >= 1, 3, 4)
g1 = {k: v for k, v in s["null_distribution"].items() if k.startswith("wc_linked_")}
mac("GOneDepartCount", str(sum(v["g1_verdict"] == "DEPARTS" for v in g1.values())))
mac("GOneTotalCount", str(len(g1)))

# ---- E29: annotator model (i.i.d. difficulty)
a = json.loads((X / "E29/E29_fit.json").read_text())
for ds, tag in DS.items():
    mac(f"FitA{tag}", f(a[ds]["a"], sign=False))
    mac(f"FitB{tag}", f(a[ds]["b"], sign=False))
    mac(f"FitNItems{tag}", f"{a[ds]['n_items']:,}".replace(",", "{,}"))
g3 = json.loads((X / "E29/E29_g3.json").read_text())
mac("GThreeCorr", f"{g3['pearson_corr']:.3f}")
mac("GThreeMaxRelBiasPct", f"{100 * g3['max_rel_bias']:.1f}")
sim = json.loads((X / "E29/E29_simcheck.json").read_text())
for ds, tag in DS.items():
    mac(f"ConsecHCorr{tag}", f(sim[ds]["real"]["consec_H_corr"], sign=False))

# ---- E30: AR(1) annotator model
p30 = X / "E30/E30_fit.json"
if p30.exists():
    r = json.loads(p30.read_text())
    for ds, tag in DS.items():
        if ds in r:
            mac(f"ArFitB{tag}", f(r[ds]["b"], sign=False))
            mac(f"ArFitRho{tag}", f(r[ds]["rho"], sign=False))

# ---- E30b: M3ED refit by direct maximisation of the truncated likelihood
p30b = X / "E30/E30b_m3ed.json"
if p30b.exists():
    r = json.loads(p30b.read_text())
    mac("ArFitBMthreeedDirect", f(r["best"]["b"], sign=False))
    mac("ArFitRhoMthreeedDirect", f(r["best"]["rho"], sign=False))
    mac("PpcConsecHMthreeedDirect", f(r["ppc"]["consec_H_corr_mean"], sign=False))

# ---- E32: calibration map, gate G2, oracle check, real-data Neyman interval
e32 = json.loads((X / "E32/E32_results.json").read_text())
GW = {"-1.2": "MinusOnePointTwo", "-0.8": "MinusPointEight", "-0.4": "MinusPointFour", "0.0": "Zero", "0.4": "PlusPointFour"}
for g, t in GW.items():
    gs = e32["calibration_map"]["grid_stats"][g]
    mac(f"CalMapMean{t}", f(gs["mean"]))
    mac(f"CalMapLo{t}", f(gs["q2_5"]))
    mac(f"CalMapHi{t}", f(gs["q97_5"]))
    o = e32["oracle_check"][g]
    mac(f"OracleMean{t}", f(o["mean"]))
    if g in e32["g2"]["per_gamma"]:
        v = e32["g2"]["per_gamma"][g]
        mac(f"GTwoBias{t}", f(v["bias"]))
        mac(f"GTwoCov{t}", f(v["coverage"], sign=False))
mac("NRepsCal", str(e32["config"]["n_cal_reps"]))
mac("NRepsGTwo", str(e32["config"]["n_g2_reps"]))
mac("NRepsOracle", str(e32["config"]["n_orc_reps"]))
mac("GTwoPassCount", str(sum(bool(v["g2_pass"]) for v in e32["g2"]["per_gamma"].values())))
mac("GTwoTotalCount", str(len(e32["g2"]["per_gamma"])))
ny = e32["real_data_neyman_interval"]
mac("RealNeymanLo", f(ny["lo_bound"]))
mac("RealNeymanHiGrid", f(ny["hi_bound"]))
assert ny["open_hi"] and ny["contains_zero"]

# ---- E32 follow-up (NOT pre-registered): extended grid to +0.8/+1.2, re-test of G2 at +0.4
fu = json.loads((X / "E32/E32_followup_extended_grid.json").read_text())
g = fu["g2_extended_gamma_0p4"]
mac("FuGTwoBiasPlusPointFour", f(g["bias"]))
mac("FuGTwoCovPlusPointFour", f(g["coverage"], sign=False))
mac("FuNValidPlusPointFour", str(g["n_valid_cal"]))
mac("FuNPlusPointFour", str(g["n"]))
ci = fu["real_data_ext"]["neyman_ci"]
assert not ci["open_lo"] and not ci["open_hi"] and ci["contains_zero"]
mac("FuRealNeymanLo", f(ci["lo_bound"]))
mac("FuRealNeymanHi", f(ci["hi_bound"]))
mac("FuRealGammaCal", f(fu["real_data_ext"]["gamma_cal"]))
for gg, t in (("+0.8", "PlusPointEight"), ("+1.2", "PlusOnePointTwo")):
    st = fu["new_gamma_stats"][gg]
    mac(f"CalMapMean{t}", f(st["mean"]))
    mac(f"CalMapLo{t}", f(st["q2_5"]))
    mac(f"CalMapHi{t}", f(st["q97_5"]))
# share of the original G2 hold-out reps at gamma=+0.4 whose naive estimate lay above the top of the
# 5-point mean curve (not invertible, hence excluded from the G2 bias computation)
m_top = max(e32["calibration_map"]["m_arr"])
g2ck = json.loads((X / "E32/E32_g2_ckpt.json").read_text())["g2"]
obs04 = [r["obs"]["gamma_hat"] for r in g2ck if r["gamma_inj"] == 0.4 and r["obs"]["converged"]]
mac("GTwoOutOfRangePctPlusPointFour", f"{100 * sum(v > m_top for v in obs04) / len(obs04):.0f}")

# ---- E33c: per-corpus diagnostic test, S1 = accuracy-linked pipeline, S2 = AR(1) annotator model
e33 = json.loads((X / "E33c/E33c_results.json").read_text())
# E40: the S2 (primary) rows rerun with B = 2000 (median-centred two-sided p); S1 rows stay at E33c (B = 200)
e40 = json.loads((X / "E40/E40_summary.json").read_text())
CW = {"friends": "Friends", "emotionpush": "EmotionPush", "m3ed": "Mthreeed"}
diag_reject = {}
for c, t in CW.items():
    mac(f"CorpusGamma{t}", f(e33["real_gammas"][c]["gamma_hat"]))
    assert abs(e40[c]["real"] - e33["real_gammas"][c]["gamma_hat"]) < 1e-9
    d = e33["decisions"][f"{c}_S1"]
    mac(f"DiagNullMean{t}One", f(d["null_mean"]))
    mac(f"DiagNullSd{t}One", f(d["null_std"], sign=False))
    mac(f"DiagNullLo{t}One", f(d["null_q2_5"]))
    mac(f"DiagNullHi{t}One", f(d["null_q97_5"]))
    mac(f"DiagP{t}One", f(P2["E33c"][f"{c}_S1"]["p"], 3, sign=False))
    diag_reject[f"{c}_S1"] = bool(d["reject_gamma0"])
    d = e40[c]
    mac(f"DiagNullMean{t}Two", f(d["mean"]))
    mac(f"DiagNullSd{t}Two", f(d["sd"], sign=False))
    mac(f"DiagNullLo{t}Two", f(d["q2_5"]))
    mac(f"DiagNullHi{t}Two", f(d["q97_5"]))
    mac(f"DiagP{t}Two", fp(0.0 if d["p_two_sided"] <= 1 / (d["B"] + 1) + 1e-12 else d["p_two_sided"], d["B"]))
    diag_reject[f"{c}_S2"] = bool(d["reject"])
    sn = e33["sanity"][c]
    mac(f"SanityRealHmean{t}", f(sn["real_H_mean"], sign=False))
    mac(f"SanitySOneHmean{t}", f(sn["S1_H_mean"]["mean"], sign=False))
    mac(f"SanitySTwoHmean{t}", f(sn["S2_H_mean"]["mean"], sign=False))
    mac(f"SanitySTwoConsec{t}", f(sn["S2_consec_H_corr"]["mean"], sign=False))
assert len({e40[c]["B"] for c in CW}) == 1
mac("NRepsDiagSTwo", f"{e40['friends']['B']:,}".replace(",", "{,}"))
mac("DiagRejectCount", str(sum(diag_reject.values())))
mac("DiagTotalCount", str(len(diag_reject)))
mac("NRepsDiag", str(e33["config"]["n_reps"]))

# direction checks for sentences in the text (S1 simulates LOWER mean vote entropy than the real data)
assert all(e33["sanity"][c]["S1_H_mean"]["mean"] < e33["sanity"][c]["real_H_mean"] for c in CW), "S1 H direction changed"
mac("DiagRejectList", ", ".join(f"{CW[k.rsplit('_', 1)[0]]}" for k, v in diag_reject.items() if v)
    .replace("Mthreeed", "M3ED") or "none")

# ---- E35: full decision table (X3), power and cross-simulator type-I error (X2), S1 entropy sensitivity (X6)
e35 = json.loads((X / "E35/E35_results.json").read_text())
ET = {"hard_wc": "HardWc", "hard_rh": "HardRh", "soft_wc": "SoftWc", "soft_rh": "SoftRh"}
ST = {"S1": "SOne", "S2": "STwo", "C0": "CZero"}
for est, et in ET.items():
    mac(f"TabReal{et}", f(e35["real_gammas"][est]["gamma_hat"] if isinstance(e35["real_gammas"][est], dict)
                          else e35["real_gammas"][est]))
    for sim, st in ST.items():
        d = e35["x3_table"][f"{est}_{sim}"]
        mac(f"Tab{et}{st}Mean", f(d["null_mean"]))
        mac(f"Tab{et}{st}Sd", f(d["null_std"], sign=False))
        mac(f"Tab{et}{st}Lo", f(d["null_q2_5"]))
        mac(f"Tab{et}{st}Hi", f(d["null_q97_5"]))
        mac(f"Tab{et}{st}P", fp(d["emp_p"] if d["emp_p"] > 1 / (d["B"] + 1) + 1e-12 else 0.0, d["B"]))
        mac(f"Tab{et}{st}Rej", "yes" if d["reject"] else "no")


def holm(pdict):
    items = sorted(pdict.items(), key=lambda kv: kv[1])
    n, run, out = len(items), 0.0, {}
    for i, (k, p) in enumerate(items):
        run = max(run, min(1.0, (n - i) * p))
        out[k] = run
    return out


main_keys = [f"{e}_{s}" for e in ("hard_wc", "hard_rh") for s in ST]
h_main = holm({k: e35["x3_table"][k]["emp_p"] for k in main_keys})
h_full = holm({k: v["emp_p"] for k, v in e35["x3_table"].items()})
mac("TabHolmMainNReject", str(sum(v < 0.05 for v in h_main.values())))
mac("TabHolmMainMin", f(min(h_main.values()), 3, sign=False))
mac("TabHolmFullNReject", str(sum(v < 0.05 for v in h_full.values())))
mac("TabHolmFullMin", f(min(h_full.values()), 3, sign=False))
mac("TabNReps", str(e35["config"]["N_NULL_REPS"]))
mac("TabPFloor", f(1 / (e35["config"]["N_NULL_REPS"] + 1), 3, sign=False))
mac("TabNRejectRaw", str(sum(v["reject"] for v in e35["x3_table"].values())))
GW = {-1.2: "MinusOnePointTwo", -0.8: "MinusPointEight", -0.4: "MinusPointFour", -0.2: "MinusPointTwo",
      0.4: "PlusPointFour"}
for g, gt in GW.items():
    for sim, st in (("S1", "SOne"), ("S2", "STwo")):
        d = e35["x2_power"][f"power_{g}_{sim}"]
        mac(f"Pow{gt}{st}", f"{d['reject_rate']:.2f}")
mac("NRepsPow", str(e35["config"]["N_POWER_REPS"]))
pc = json.loads((X / "E35/posthoc_power_vs_c0.json").read_text())
for r in pc["rows"]:
    gt = GW[r["gamma_true"]]
    mac(f"Pow{gt}CZero", f"{r['rate']:.2f}")
    mac(f"Pow{gt}CZeroLo", f"{r['wilson95'][0]:.2f}")
    mac(f"Pow{gt}CZeroHi", f"{r['wilson95'][1]:.2f}")
    mac(f"PowMeanHat{gt}", f(r["gamma_hat_mean"]))
CT = {"S1_vs_S2": "SOneInSTwo", "S2_vs_S1": "STwoInSOne", "C0_vs_S1": "CZeroInSOne", "C0_vs_S2": "CZeroInSTwo"}
for k, t in CT.items():
    d = e35["x2_cross_type1"][k]
    mac(f"Cross{t}", f"{d['rate']:.2f}")
    mac(f"Cross{t}Lo", f"{d['wilson_lo']:.2f}")
    mac(f"Cross{t}Hi", f"{d['wilson_hi']:.2f}")
x6 = e35["x6"]
mac("XsixDelta", f(x6["delta"], 3))
mac("XsixLo", f(x6["decision"]["q2_5"]))
mac("XsixHi", f(x6["decision"]["q97_5"]))
mac("XsixRej", "yes" if x6["decision"]["reject"] else "no")
mac("XsixHmean", f(x6["decision"]["H_mean"], sign=False))
for k, t in (("real", "Real"), ("S1", "SOne"), ("S2", "STwo"), ("C0", "CZero"), ("S1'", "SOnePrime")):
    mac(f"ElHmean{t}", f(e35["sanity"][k]["H_mean"], sign=False))
    mac(f"ElConsec{t}", f(e35["sanity"][k]["consec_H_corr"], sign=False))
assert e35["sanity"]["S1"]["H_mean"] < e35["sanity"]["real"]["H_mean"], "S1 EL-wide H direction changed"

# ---- E31c: numerical unimodality and a second downstream model (multinomial logit)
e31c = json.loads((X / "E31/E31c_results.json").read_text())
rows = e31c["rows"]
mac("UniNSettings", f"{len(rows):,}".replace(",", "{,}"))
mac("UniNUnimodal", f"{sum(r['n_local_max'] <= 1 for r in rows):,}".replace(",", "{,}"))
neg = [r for r in rows if r["cov_h_s"] < -1e-12]
for mdl, tag in (("M1", "One"), ("M2", "Two")):
    sub = [r for r in neg if r["model"] == mdl]
    mac(f"UniNegModel{tag}", str(sum(r["gamma_star"] < 0 for r in sub)))
    mac(f"UniCovNegModel{tag}", str(len(sub)))

# ---- E31: Proposition 1
p1 = json.loads((X / "E31/E31_results.json").read_text())
BW = {0.0: "Zero", 0.25: "QuarterB", 0.5: "HalfB", 0.8: "PointEightB", 1.2: "OnePointTwoB", 1.6: "OnePointSixB"}
for row in p1["rows"]:
    t = BW[row["b"]]
    mac(f"PropGammaStar{t}", f(row["gamma_star"]))
    mac(f"PropMcMean{t}", f(row["mc_gamma_mean"]))
    mac(f"PropMcSd{t}", f(row["mc_gamma_sd"], sign=False))
mac("PropK", str(p1["K"]))

# ---- E31b: Proposition 1 with homogeneous annotators (constant accuracy q)
p1b = json.loads((X / "E31/E31b_results.json").read_text())
QW = {0.6: "PointSix", 0.7: "PointSeven", 0.8: "PointEight"}
for row in p1b["rows"]:
    t = QW[row["q"]]
    mac(f"HomGammaStarQ{t}", f(row["gamma_star"]))
    mac(f"HomMcMeanQ{t}", f(row["mc_gamma_mean"]))
    mac(f"HomMcSdQ{t}", f(row["mc_gamma_sd"], sign=False))
    mac(f"HomFlipPctQ{t}", f"{100 * row['overall_flip']:.1f}")

# ---- E34e: latent-mark correction under a matched DGP (one latent difficulty drives excitation and accuracy)
e34e = json.loads((X / "E34e/E34e_summary.json").read_text())
for key, tag in (("g+0.0", "GZero"), ("g-0.4", "GMinusPointFour")):
    for est, et in (("hard", "Hard"), ("ds_corr", "Corr")):
        v = e34e[f"{key}_{est}"]
        mac(f"LatMark{et}{tag}Mean", f(v["mean"]))
        mac(f"LatMark{et}{tag}Se", f(v["se"], sign=False))
        mac(f"LatMark{et}{tag}N", str(v["n"]))
assert e34e["g+0.0_hard"]["mean"] < -2 * e34e["g+0.0_hard"]["se"], "E34e: artifact direction changed"
assert e34e["g+0.0_ds_corr"]["mean"] > 2 * e34e["g+0.0_ds_corr"]["se"], "E34e: overshoot direction changed"

# ---- E36: oracle over-shoot (modifier definition x sample size), E36b: post-hoc check without refinement
e36 = json.loads((X / "E36/E36_results.json").read_text())["aggregate"]
GW36 = {"g0p0": "Zero", "gm0p4": "MinusPointFour", "gm0p8": "MinusPointEight"}
for g, gt in GW36.items():
    for n in (500, 2000, 8000):
        for mod, mt in (("wc", "Wc"), ("rh", "Rh")):
            v = e36[f"{mod}_n{n}_{g}"]
            nt = {500: "FiveHundred", 2000: "TwoThousand", 8000: "EightThousand"}[n]
            mac(f"Orc{mt}{nt}{gt}Bias", f(v["mean_bias"]))
            mac(f"Orc{mt}{nt}{gt}Se", f(v["mc_se"], 3, sign=False))
mac("NRepsOrc", str(json.loads((X / "E36/E36_results.json").read_text())["config"]["n_reps"]))
e36b = json.loads((X / "E36/E36b_results.json").read_text())["summary"]
for g, gt in (("g-0.4", "MinusPointFour"), ("g-0.8", "MinusPointEight")):
    for mod, mt in (("rh", "Rh"), ("wc", "Wc")):
        v = e36b[f"{g}_{mod}"]
        mac(f"OrcNoRef{mt}{gt}Bias", f(v["bias"], 3))
        mac(f"OrcNoRef{mt}{gt}Se", f(v["mc_se"], 3, sign=False))
mac("NRepsOrcNoRef", str(e36b["g-0.4_rh"]["n"]))
assert abs(e36b["g-0.4_rh"]["bias"]) < 2 * e36b["g-0.4_rh"]["mc_se"] and abs(e36b["g-0.8_rh"]["bias"]) < 2 * e36b["g-0.8_rh"]["mc_se"]

# ---- E34f: exploratory decomposition of the latent-mark overshoot (gamma = 0, same DGP as E34e)
e34f = json.loads((X / "E34f/E34f_results.json").read_text())["summary"]
for key, tag in (("A_corr_post_H", "CorrPostH"), ("B_corr_true_H", "CorrTrueHistH"), ("C_corr_post_u", "CorrPostU"),
                 ("D_hard_u", "HardU"), ("E_hard_H", "HardH")):
    mac(f"Mech{tag}Mean", f(e34f[key]["mean"]))
    mac(f"Mech{tag}Se", f(e34f[key]["se"], sign=False))
mac("NRepsMech", str(e34f["A_corr_post_H"]["n"]))

# ---- E37: MC-SIMEX (integer lambda 1, 2, 3; quadratic and linear extrapolation)
e37 = json.loads((X / "E37/E37_results.json").read_text())
for key, tag in (("g+0.0", "GZero"), ("g-0.4", "GMinusPointFour")):
    for est, et in (("naive", "Naive"), ("simex_quad", "Quad"), ("simex_lin", "Lin")):
        v = e37["summary"][f"{key}_{est}"]
        mac(f"Simex{et}{tag}Mean", f(v["mean"]))
        mac(f"Simex{et}{tag}Se", f(v["se"], sign=False))
        mac(f"Simex{et}{tag}N", str(v["n"]))
mac("NRepsSimex", str(sum(1 for r in e37["rows"] if r["gamma"] == 0.0)))

e37x = json.loads((X / "E37/E37_extra_summary.json").read_text())
for g, gt in (("0.0", "GZero"), ("-0.4", "GMinusPointFour")):
    for i, lt in enumerate(("Zero", "One", "Two", "Three")):
        mac(f"SimexPath{gt}Lam{lt}", f(e37x["path_mean"][g][i]))
    mac(f"SimexExcluded{gt}", str(e37x["n_excluded"][g]))
mac("SimexFracNonStochPct", f"{100 * e37x['frac_events_nonstochastic_fractional']:.0f}")
mac("SimexNEventsChecked", f"{e37x['n_events_checked']:,}".replace(",", "{,}"))

# ---- E31d: annotator heterogeneity (fixed annotator-specific accuracies, exact enumeration)
e31d = json.loads((X / "E31/E31d_results.json").read_text())["rows"]
mac("HetNSettings", str(len(e31d)))
mac("HetNNegative", str(sum(r["gamma_star"] < 0 for r in e31d)))
mac("HetNUnimodal", str(sum(r["n_local_max"] <= 1 for r in e31d)))
mac("HetMaxSd", f(max(r["sd_q"] for r in e31d), sign=False))
for K, kt in ((3, "KThree"), (7, "KSeven")):
    for mq, mt in ((0.6, "PointSix"), (0.7, "PointSeven")):
        for sd, st in ((0.0, "SdZero"), (0.2, "SdPointTwo")):
            v = [r for r in e31d if r["K"] == K and r["mean_q"] == mq and r["sd_q"] == sd and r["model"] == "M1"][0]
            mac(f"Het{kt}{mt}{st}", f(v["gamma_star"]))
# full heterogeneity grid for the supplementary table
SDW = {0.0: "Zero", 0.05: "PointZeroFive", 0.1: "PointOne", 0.15: "PointOneFive", 0.2: "PointTwo"}
for r in e31d:
    kt = {3: "KThree", 7: "KSeven"}[r["K"]]
    mt = {0.6: "PointSix", 0.7: "PointSeven"}[r["mean_q"]]
    mac(f"HetGrid{kt}{mt}Sd{SDW[r['sd_q']]}{ {'M1': 'MOne', 'M2': 'MTwo'}[r['model']] }", f(r["gamma_star"]))

# ---- E39: posterior predictive check of the null simulators (EL-wide, 20 simulated data sets each)
e39 = json.loads((X / "E39/E39_ppc.json").read_text())
PP = {"H_mean": "HMean", "H_sd": "HSd", "H_q50": "HMedian", "lag1_corr_H": "LagOne", "unanimous_rate": "Unanimous",
      "margin_mean": "Margin", "pairwise_agreement": "PairAgree"}
for k, kt in PP.items():
    mac(f"Ppc{kt}Real", f(e39["real"][k], sign=False))
    for sim, st in (("S1", "SOne"), ("S2", "STwo"), ("C0", "CZero")):
        mac(f"Ppc{kt}{st}", f(e39[sim][k]["mean"], sign=False))
mac("NRepsPpc", "20")

# ---- E38: primary nulls (HM/WC under S2 and C0, EL-wide) with B = 2000; median-centred two-sided p
e38 = json.loads((X / "E38/E38_summary.json").read_text())
_r = e35["real_gammas"]["hard_wc"]
assert abs(e38["real_hard_wc"] - (_r["gamma_hat"] if isinstance(_r, dict) else _r)) < 1e-9
assert e38["S2"]["B"] == e38["C0"]["B"]
for sim, st in (("S2", "STwo"), ("C0", "CZero")):
    d = e38[sim]
    mac(f"BigB{st}Mean", f(d["mean"]))
    mac(f"BigB{st}Sd", f(d["sd"], sign=False))
    mac(f"BigB{st}Lo", f(d["q2_5"]))
    mac(f"BigB{st}Hi", f(d["q97_5"]))
    mac(f"BigB{st}P", fp(0.0 if d["p_two_sided"] <= 1 / (d["B"] + 1) + 1e-12 else d["p_two_sided"], d["B"]))
    mac(f"BigB{st}Rej", "yes" if d["reject"] else "no")
mac("BigBN", f"{e38['S2']['B']:,}".replace(",", "{,}"))
h_bigb = holm({s: e38[s]["p_two_sided"] for s in ("S2", "C0")})
mac("BigBHolmNReject", str(sum(v < 0.05 for v in h_bigb.values())))

out = "\n".join(lines) + "\n"
(HERE / "numbers.tex").write_text(out)
print(f"wrote {len(lines) - 1} macros -> {HERE / 'numbers.tex'}")
